import express from 'express';
import cors from 'cors';
import authRoutes from './routes/auth.routes';
import businessRoutes from './routes/business.routes';
import paymentRoutes from './routes/payment.routes';
import adminRoutes from './routes/admin.routes';
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/businesses', businessRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/admin', adminRoutes);
app.listen(process.env.PORT || 4000, () => console.log(`✅ Backend running on port ${process.env.PORT}`));